// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using SampleCA.Application.Common.Models.Transaction;
using SampleCA.Domain.Entities.AESTraining.Entities.AESTraining;
using SampleCA.Infrastructure.Persistence;
using SampleCA.Infrastructure.Persistence.Persistence.Configurations;
using System;
using System.Collections.Generic;
#nullable disable

namespace SampleCA.Infrastructure.Persistence.Persistence
{
    public partial class AESTrainingContext : DbContext
    {
        public AESTrainingContext()
        {
        }

        public AESTrainingContext(DbContextOptions<AESTrainingContext> options)
            : base(options)
        {
        }
        public virtual DbSet<TransactionDatas> TransactionDatas { get; set; }
        public virtual DbSet<TransactionGCEDatas> TransactionGCEDatas { get; set; }
        public virtual DbSet<TransactionGCRDatas> TransactionGCRDatas { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.TransactionDatasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TransactionGCEDatasConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TransactionGCRDatasConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
