// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SampleCA.Domain.Entities.AESTraining.Entities.AESTraining;
using SampleCA.Infrastructure.Persistence;
using SampleCA.Infrastructure.Persistence.Persistence;
using System;
using System.Collections.Generic;

namespace SampleCA.Infrastructure.Persistence.Persistence.Configurations
{
    public partial class TransactionGCRDatasConfiguration : IEntityTypeConfiguration<TransactionGCRDatas>
    {
        public void Configure(EntityTypeBuilder<TransactionGCRDatas> entity)
        {
            entity.Property(e => e.AgtBizName).HasMaxLength(456);

            entity.Property(e => e.AgtCEANo).HasMaxLength(50);

            entity.Property(e => e.CategoryDisplay).HasMaxLength(100);

            entity.Property(e => e.CategoryID).HasDefaultValueSql("((1))");

            entity.Property(e => e.RcvDate).HasColumnType("datetime");

            entity.Property(e => e.RoleDisplay).HasMaxLength(100);

            entity.Property(e => e.TransSource).HasMaxLength(10);

            entity.Property(e => e.TypeID).HasDefaultValueSql("((1))");
            entity.HasOne(k => k.TransactionData)
.WithMany(k => k.TransactionGCRDatas)
.HasForeignKey(k => k.TransID);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransactionGCRDatas> entity);
    }
}
