// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SampleCA.Domain.Entities.AESTraining.Entities.AESTraining;
using SampleCA.Infrastructure.Persistence;
using SampleCA.Infrastructure.Persistence.Persistence;
using System;
using System.Collections.Generic;

namespace SampleCA.Infrastructure.Persistence.Persistence.Configurations
{
    public partial class TransactionGCEDatasConfiguration : IEntityTypeConfiguration<TransactionGCEDatas>
    {
        public void Configure(EntityTypeBuilder<TransactionGCEDatas> entity)
        {
            entity.Property(e => e.AgtBizName).HasMaxLength(456);

            entity.Property(e => e.AgtCEANo).HasMaxLength(50);

            entity.Property(e => e.CategoryDisplay).HasMaxLength(100);

            entity.Property(e => e.KeyinDate).HasColumnType("datetime");

            entity.Property(e => e.OptionDate).HasColumnType("datetime");

            entity.Property(e => e.RoleDisplay).HasMaxLength(100);

            entity.Property(e => e.SubDate).HasColumnType("datetime");

            entity.Property(e => e.TypeID).HasDefaultValueSql("((1))");
            entity.HasOne(k => k.TransactionData)
.WithMany(k => k.TransactionGCEDatas)
.HasForeignKey(k => k.TransID);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransactionGCEDatas> entity);
    }
}
