// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SampleCA.Domain.Entities.AESTraining.Entities.AESTraining;
using SampleCA.Infrastructure.Persistence;
using SampleCA.Infrastructure.Persistence.Persistence;
using System;
using System.Collections.Generic;

namespace SampleCA.Infrastructure.Persistence.Persistence.Configurations
{
    public partial class TransactionDatasConfiguration : IEntityTypeConfiguration<TransactionDatas>
    {
        public void Configure(EntityTypeBuilder<TransactionDatas> entity)
        {
            entity.HasKey(e => e.TransID)
                .HasName("PK__Transact__9E5DDB1C8609EDB4");

            entity.Property(e => e.TransID).ValueGeneratedNever();

            entity.Property(e => e.ClosingAgtBizName).HasMaxLength(456);

            entity.Property(e => e.ClosingAgtCEANo).HasMaxLength(50);

            entity.Property(e => e.CultureCode).HasMaxLength(10);

            entity.Property(e => e.CurrencyType).HasMaxLength(10);

            entity.Property(e => e.GeneratedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("(getdate())");

            entity.Property(e => e.HseNo).HasMaxLength(100);

            entity.Property(e => e.KeyinDate).HasColumnType("datetime");

            entity.Property(e => e.LastUpdater).HasMaxLength(100);

            entity.Property(e => e.OptionDate).HasColumnType("datetime");

            entity.Property(e => e.ProjectName).HasMaxLength(456);

            entity.Property(e => e.PropertyCategory).HasMaxLength(50);

            entity.Property(e => e.PropertyModel).HasMaxLength(100);

            entity.Property(e => e.PropertyType).HasMaxLength(50);

            entity.Property(e => e.SalesType).HasMaxLength(50);

            entity.Property(e => e.StreetName).HasMaxLength(456);

            entity.Property(e => e.SubDate).HasColumnType("datetime");

            entity.Property(e => e.TransType).HasMaxLength(50);

            entity.Property(e => e.TransTypeID).HasDefaultValueSql("((1))");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TransactionDatas> entity);
    }
}
