// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleCA.Domain.Entities.AESTraining.Entities.AESTraining
{
    public partial class TransactionDatas
    {
        public int TransID { get; set; }
        public int TransTypeID { get; set; }
        public string TransType { get; set; }
        public string PropertyType { get; set; }
        public int? PropertyCategoryID { get; set; }
        public string PropertyCategory { get; set; }
        public string PropertyModel { get; set; }
        public DateTime KeyinDate { get; set; }
        public DateTime SubDate { get; set; }
        public string SalesType { get; set; }
        public string ClosingAgtCEANo { get; set; }
        public string ClosingAgtBizName { get; set; }
        public DateTime OptionDate { get; set; }
        public string HseNo { get; set; }
        public string StreetName { get; set; }
        public string ProjectName { get; set; }
        public double TransactedPrice { get; set; }
        public double TransactionComm { get; set; }
        public string CurrencyType { get; set; }
        public string CultureCode { get; set; }
        public DateTime GeneratedDate { get; set; }
        public string LastUpdater { get; set; }

        public virtual IList<TransactionGCEDatas> TransactionGCEDatas { get; set; }
        public virtual IList<TransactionGCRDatas> TransactionGCRDatas { get; set; }
    }
}